extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:jest/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/ban-ts-comment": "off"
  "@typescript-eslint/no-explicit-any": "off"
  #TODO: fix
  # "@typescript-eslint/no-floating-promises":
  #   - error
  #   - ignoreIIFE: true
  #     ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  #TODO: fix
  "@typescript-eslint/no-non-null-assertion": "off"
  #TODO: fix
  "jest/no-disabled-tests": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "_"
      varsIgnorePattern: "_"