import { CHAIN_TO_MAINNET_TOKEN_ADDRESS_MAP, MAINNET_ERC20_ASSETS } from './mainnet/erc20';
import { MAINNET_NATIVE_ASSETS } from './mainnet/native';

const MAINNET_ASSETS = { ...MAINNET_NATIVE_ASSETS, ...MAINNET_ERC20_ASSETS };

export { MAINNET_ASSETS, CHAIN_TO_MAINNET_TOKEN_ADDRESS_MAP };
