export const DEBRIDGE_ERROR_SOURCE_NAME = 'Debridge API';

export const DEBRIDGE_ERRORS = {
  INVALID_QUERY_PARAMETERS: 'INVALID_QUERY_PARAMETERS',
  SOURCE_AND_DESTINATION_CHAINS_ARE_EQUAL: 'SOURCE_AND_DESTINATION_CHAINS_ARE_EQUAL',
  INCLUDED_GAS_FEE_NOT_COVERED_BY_INPUT_AMOUNT: 'INCLUDED_GAS_FEE_NOT_COVERED_BY_INPUT_AMOUNT',
  INCLUDED_GAS_FEE_CANNOT_BE_ESTIMATED_FOR_TRANSACTION_BUNDLE:
    'INCLUDED_GAS_FEE_CANNOT_BE_ESTIMATED_FOR_TRANSACTION_BUNDLE',
  CONNECTOR_1INCH_RETURNED_ERROR: 'CONNECTOR_1INCH_RETURNED_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INTERNAL_SDK_ERROR: 'INTERNAL_SDK_ERROR',
};

export type DebridgeError = {
  errorCode: number;
  errorId: string;
  errorMessage: string;
  errorPayload: any;
};
