
// TODO: is this the same as store/types.ts ?
export const SwapProviderType = {
  LIQUALITY: 'LIQUALITY',
  UNISWAPV2: 'UNISWAPV2',
  ONEINCHV4: 'ONEINCHV4',
  THORCHAIN: 'THORCHAIN',
  LIQUALITYBOOST_NATIVE_TO_ERC20: 'LIQUALITYBOOST_NATIVE_TO_ERC20',
  LIQUALITYBOOST_ERC20_TO_NATIVE: 'LIQUALITYBOOST_ERC20_TO_NATIVE',
  FASTBTC: 'FASTBTC',
  SOVRYN: 'SOVRYN',
  ASTROPORT: 'ASTROPORT'
}