export enum SwapProviderType {
  LIQUALITY = 'LIQUALITY',
  UNISWAPV2 = 'UNISWAPV2',
  ONEINCHV4 = 'ONEINCHV4',
  THORCHAIN = 'THORCHAIN',
  LIQUALITYBOOST = 'LIQUALITYBOOST',
  FASTBTC = 'FASTBTC',
  SOVRYN = 'SOVRYN',
  ASTROPORT = 'ASTROPORT',
}
